"""baseline

Revision ID: ba7cbc14b3a2
Revises:
Create Date: 2026-09-29 11:56:46.159536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7cbc14b3a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personeel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gebruikersnaam', sa.Text(), nullable=False),
    sa.Column('wachtwoord_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gebruikersnaam')
    )
    op.create_table('reserveringen',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('naam', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('telefoon', sa.Text(), nullable=False),
    sa.Column('datum', sa.Text(), nullable=False),
    sa.Column('tijd', sa.Text(), nullable=False),
    sa.Column('aantal', sa.Integer(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserveringen')
    op.drop_table('personeel')
    # ### end Alembic commands ###
